apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: jenkins
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    app: jenkins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  strategy: {}
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - image: jenkins/jenkins:lts
        name: jenkins
        ports:
        - name: http-port
          containerPort: 8080
        volumeMounts:
        - name: jenkins-volume
          mountPath: /var/jenkins_volume
        resources: {}
      volumes:
      - name: jenkins-volume
        emptyDir: {}
status: {}