apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rules
spec:
    ingressClassName: nginx
    rules:
       - http:
          paths:
            - pathType: Prefix
              backend:
                service:
                  name: jenkins
                  port:
                    number: 8080
              path: /